.TH "Android_GUIScript" 3 "Thu Nov 26 2020" "Version 1.0" "FloorIsLava" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Android_GUIScript \- Script for integration of android touch screen buttons  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Vector4 \fBGetInputValues\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBjumping\fP = false"
.br
.RI "Vector4 to keep track of jump "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.RI "Add all listeners to buttons "
.ti -1c
.RI "void \fBOnMoveFowardsButtonDown\fP ()"
.br
.RI "Listener function for button to allow touch input "
.ti -1c
.RI "void \fBOnMoveFowardsButtonUp\fP ()"
.br
.RI "Listener function for button to allow touch input "
.ti -1c
.RI "void \fBOnMoveBackwardsButtonDown\fP ()"
.br
.RI "Listener function for button to allow touch input "
.ti -1c
.RI "void \fBOnMoveBackwardsButtonUp\fP ()"
.br
.RI "Listener function for button to allow touch input "
.ti -1c
.RI "void \fBOnRotateLeftButtonDown\fP ()"
.br
.RI "Listener function for button to allow touch input "
.ti -1c
.RI "void \fBOnRotateLeftButtonUp\fP ()"
.br
.RI "Listener function for button to allow touch input "
.ti -1c
.RI "void \fBOnRotateRightButtonDown\fP ()"
.br
.RI "Listener function for button to allow touch input "
.ti -1c
.RI "void \fBOnRotateRightButtonUp\fP ()"
.br
.RI "Listener function for button to allow touch input "
.ti -1c
.RI "void \fBOnJumpButton\fP ()"
.br
.RI "Listener function for button to allow touch input "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBTouchButton\fP \fBmoveFowardsButton\fP"
.br
.RI "Touchscreen input button reference "
.ti -1c
.RI "\fBTouchButton\fP \fBrotateLeftButton\fP"
.br
.RI "Touchscreen input button reference "
.ti -1c
.RI "\fBTouchButton\fP \fBrotateRightButton\fP"
.br
.RI "Touchscreen input button reference "
.ti -1c
.RI "\fBTouchButton\fP \fBmoveBackwardsButton\fP"
.br
.RI "Touchscreen input button reference "
.ti -1c
.RI "\fBTouchButton\fP \fBjumpButton\fP"
.br
.RI "Touchscreen input button reference "
.ti -1c
.RI "Vector4 \fBinputValues\fP = new Vector4()"
.br
.RI "Vector4 to keep track of all input buttons "
.in -1c
.SH "Detailed Description"
.PP 
Script for integration of android touch screen buttons 


.PP
Definition at line 6 of file Android_GUIScript\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Vector4 Android_GUIScript\&.GetInputValues ()"

.PP
Definition at line 137 of file Android_GUIScript\&.cs\&.
.PP
.nf
138     {
139         return inputValues;
140     }
.fi
.SS "void Android_GUIScript\&.OnJumpButton ()\fC [private]\fP"

.PP
Listener function for button to allow touch input 
.PP
Definition at line 132 of file Android_GUIScript\&.cs\&.
.PP
.nf
133     {
134         jumping = true;
135     }
.fi
.SS "void Android_GUIScript\&.OnMoveBackwardsButtonDown ()\fC [private]\fP"

.PP
Listener function for button to allow touch input 
.PP
Definition at line 84 of file Android_GUIScript\&.cs\&.
.PP
.nf
85     {
86         inputValues\&.y = 1\&.0F;
87     }
.fi
.SS "void Android_GUIScript\&.OnMoveBackwardsButtonUp ()\fC [private]\fP"

.PP
Listener function for button to allow touch input 
.PP
Definition at line 92 of file Android_GUIScript\&.cs\&.
.PP
.nf
93     {
94         inputValues\&.y = 0\&.0F;
95     }
.fi
.SS "void Android_GUIScript\&.OnMoveFowardsButtonDown ()\fC [private]\fP"

.PP
Listener function for button to allow touch input 
.PP
Definition at line 68 of file Android_GUIScript\&.cs\&.
.PP
.nf
69     {
70         inputValues\&.x = 1\&.0F;
71     }
.fi
.SS "void Android_GUIScript\&.OnMoveFowardsButtonUp ()\fC [private]\fP"

.PP
Listener function for button to allow touch input 
.PP
Definition at line 76 of file Android_GUIScript\&.cs\&.
.PP
.nf
77     {
78         inputValues\&.x = 0\&.0F;
79     }
.fi
.SS "void Android_GUIScript\&.OnRotateLeftButtonDown ()\fC [private]\fP"

.PP
Listener function for button to allow touch input 
.PP
Definition at line 100 of file Android_GUIScript\&.cs\&.
.PP
.nf
101     {
102         inputValues\&.z = 1\&.0F;
103     }
.fi
.SS "void Android_GUIScript\&.OnRotateLeftButtonUp ()\fC [private]\fP"

.PP
Listener function for button to allow touch input 
.PP
Definition at line 108 of file Android_GUIScript\&.cs\&.
.PP
.nf
109     {
110         inputValues\&.z = 0\&.0F;
111     }
.fi
.SS "void Android_GUIScript\&.OnRotateRightButtonDown ()\fC [private]\fP"

.PP
Listener function for button to allow touch input 
.PP
Definition at line 116 of file Android_GUIScript\&.cs\&.
.PP
.nf
117     {
118         inputValues\&.w = 1\&.0F;
119     }
.fi
.SS "void Android_GUIScript\&.OnRotateRightButtonUp ()\fC [private]\fP"

.PP
Listener function for button to allow touch input 
.PP
Definition at line 124 of file Android_GUIScript\&.cs\&.
.PP
.nf
125     {
126         inputValues\&.w = 0\&.0F;
127     }
.fi
.SS "void Android_GUIScript\&.Start ()\fC [private]\fP"

.PP
Add all listeners to buttons 
.PP
Definition at line 52 of file Android_GUIScript\&.cs\&.
.PP
.nf
53     {
54         moveFowardsButton\&.onButDown\&.AddListener(OnMoveFowardsButtonDown);
55         moveFowardsButton\&.onButUp\&.AddListener(OnMoveFowardsButtonUp);
56         moveBackwardsButton\&.onButDown\&.AddListener(OnMoveBackwardsButtonDown);
57         moveBackwardsButton\&.onButUp\&.AddListener(OnMoveBackwardsButtonUp);
58         rotateLeftButton\&.onButDown\&.AddListener(OnRotateLeftButtonDown);
59         rotateLeftButton\&.onButUp\&.AddListener(OnRotateLeftButtonUp);
60         rotateRightButton\&.onButDown\&.AddListener(OnRotateRightButtonDown);
61         rotateRightButton\&.onButUp\&.AddListener(OnRotateRightButtonUp);
62         jumpButton\&.onButDown\&.AddListener(OnJumpButton);
63     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "Vector4 Android_GUIScript\&.inputValues = new Vector4()\fC [private]\fP"

.PP
Vector4 to keep track of all input buttons 
.PP
Definition at line 42 of file Android_GUIScript\&.cs\&.
.SS "\fBTouchButton\fP Android_GUIScript\&.jumpButton\fC [private]\fP"

.PP
Touchscreen input button reference 
.PP
Definition at line 37 of file Android_GUIScript\&.cs\&.
.SS "bool Android_GUIScript\&.jumping = false"

.PP
Vector4 to keep track of jump 
.PP
Definition at line 47 of file Android_GUIScript\&.cs\&.
.SS "\fBTouchButton\fP Android_GUIScript\&.moveBackwardsButton\fC [private]\fP"

.PP
Touchscreen input button reference 
.PP
Definition at line 31 of file Android_GUIScript\&.cs\&.
.SS "\fBTouchButton\fP Android_GUIScript\&.moveFowardsButton\fC [private]\fP"

.PP
Touchscreen input button reference 
.PP
Definition at line 13 of file Android_GUIScript\&.cs\&.
.SS "\fBTouchButton\fP Android_GUIScript\&.rotateLeftButton\fC [private]\fP"

.PP
Touchscreen input button reference 
.PP
Definition at line 19 of file Android_GUIScript\&.cs\&.
.SS "\fBTouchButton\fP Android_GUIScript\&.rotateRightButton\fC [private]\fP"

.PP
Touchscreen input button reference 
.PP
Definition at line 25 of file Android_GUIScript\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FloorIsLava from the source code\&.
