.TH "CanvasScript" 3 "Wed Nov 25 2020" "Version 1.0" "FloorIsLava" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CanvasScript \- Class for core logic of main canvas (hud)  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonWin\fP ()"
.br
.RI "Called when the player has won, sets displayWinText to TRUE "
.ti -1c
.RI "void \fBonLoss\fP ()"
.br
.RI "Called when the player has lost, sets displayLossText to TRUE "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBwinText\fP"
.br
.RI "Reference to text which shows on win "
.ti -1c
.RI "Text \fBlossText\fP"
.br
.RI "Reference to text which shows on loss "
.ti -1c
.RI "int \fBmaxLossTextDisplayTicks\fP = 100"
.br
.RI "n of ticks the loss text exists before being disabled "
.ti -1c
.RI "int \fBmaxWinTextDisplayTicks\fP = 100"
.br
.RI "n of ticks the win text exists before being disabled "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.RI "Counts n of ticks that either win/loss text has been displayed for\&. Once reaching their max n, they are disabled\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBlossTextDisplayTicks\fP = 0"
.br
.RI "n of ticks that the loss text has been displayed "
.ti -1c
.RI "int \fBwinTextDisplayTicks\fP = 0"
.br
.RI "n of ticks that the win text has been displayed "
.ti -1c
.RI "bool \fBdisplayWinText\fP = false"
.br
.RI "set to TRUE when displaying win text "
.ti -1c
.RI "bool \fBdisplayLossText\fP = false"
.br
.RI "set to TRUE when displaying loss text "
.in -1c
.SH "Detailed Description"
.PP 
Class for core logic of main canvas (hud) 


.PP
Definition at line 7 of file CanvasScript\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void CanvasScript\&.onLoss ()"

.PP
Called when the player has lost, sets displayLossText to TRUE 
.PP
Definition at line 98 of file CanvasScript\&.cs\&.
.PP
.nf
99     {
100         displayLossText = true;
101     }
.fi
.SS "void CanvasScript\&.onWin ()"

.PP
Called when the player has won, sets displayWinText to TRUE 
.PP
Definition at line 90 of file CanvasScript\&.cs\&.
.PP
.nf
91     {
92         displayWinText = true;
93     }
.fi
.SS "void CanvasScript\&.Update ()\fC [private]\fP"

.PP
Counts n of ticks that either win/loss text has been displayed for\&. Once reaching their max n, they are disabled\&. 
.PP
Definition at line 53 of file CanvasScript\&.cs\&.
.PP
.nf
54     {
55         if (displayLossText)
56         {
57             lossTextDisplayTicks++;
58             if (lossTextDisplayTicks >= maxLossTextDisplayTicks)
59             {
60                 lossTextDisplayTicks = 0;
61                 displayLossText = false;
62             }
63         }
64         else
65         {
66             lossTextDisplayTicks = 0;
67         }
68 
69         if (displayWinText)
70         {
71             winTextDisplayTicks++;
72             if (winTextDisplayTicks >= maxWinTextDisplayTicks)
73             {
74                 lossTextDisplayTicks = 0;
75                 displayWinText = false;
76             }
77         }
78         else
79         {
80             winTextDisplayTicks = 0;
81         }
82 
83         lossText\&.enabled = displayLossText;
84         winText\&.enabled = displayWinText;
85     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "bool CanvasScript\&.displayLossText = false\fC [private]\fP"

.PP
set to TRUE when displaying loss text 
.PP
Definition at line 47 of file CanvasScript\&.cs\&.
.SS "bool CanvasScript\&.displayWinText = false\fC [private]\fP"

.PP
set to TRUE when displaying win text 
.PP
Definition at line 42 of file CanvasScript\&.cs\&.
.SS "Text CanvasScript\&.lossText"

.PP
Reference to text which shows on loss 
.PP
Definition at line 17 of file CanvasScript\&.cs\&.
.SS "int CanvasScript\&.lossTextDisplayTicks = 0\fC [private]\fP"

.PP
n of ticks that the loss text has been displayed 
.PP
Definition at line 22 of file CanvasScript\&.cs\&.
.SS "int CanvasScript\&.maxLossTextDisplayTicks = 100"

.PP
n of ticks the loss text exists before being disabled 
.PP
Definition at line 27 of file CanvasScript\&.cs\&.
.SS "int CanvasScript\&.maxWinTextDisplayTicks = 100"

.PP
n of ticks the win text exists before being disabled 
.PP
Definition at line 37 of file CanvasScript\&.cs\&.
.SS "Text CanvasScript\&.winText"

.PP
Reference to text which shows on win 
.PP
Definition at line 12 of file CanvasScript\&.cs\&.
.SS "int CanvasScript\&.winTextDisplayTicks = 0\fC [private]\fP"

.PP
n of ticks that the win text has been displayed 
.PP
Definition at line 32 of file CanvasScript\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FloorIsLava from the source code\&.
