.TH "C:/Users/disckord/Desktop/Cross Platform Development For Games/workspace/FloorIsLava/Assets/Scripts/lavaScript.cs" 3 "Thu Nov 26 2020" "Version 1.0" "FloorIsLava" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/disckord/Desktop/Cross Platform Development For Games/workspace/FloorIsLava/Assets/Scripts/lavaScript.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlavaScript\fP"
.br
.RI "Class for core logic of lava plane "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FloorIsLava from the source code\&.
