.TH "lavaScript" 3 "Tue Nov 24 2020" "Version 1.0" "FloorIsLava" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lavaScript \- Class for core logic of lava plane  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBlavaTransform\fP"
.br
.RI "Ref to lava plane transform for moving it "
.ti -1c
.RI "float \fBstartHeight\fP = \-10\&.0F"
.br
.RI "height value of lava plane when it starts "
.ti -1c
.RI "float \fBmoveSpeed\fP = 0\&.01F"
.br
.RI "number of units the lava plane moves each update vertically "
.in -1c
.SH "Detailed Description"
.PP 
Class for core logic of lava plane 


.PP
Definition at line 6 of file lavaScript\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform lavaScript\&.lavaTransform"

.PP
Ref to lava plane transform for moving it 
.PP
Definition at line 11 of file lavaScript\&.cs\&.
.SS "float lavaScript\&.moveSpeed = 0\&.01F"

.PP
number of units the lava plane moves each update vertically 
.PP
Definition at line 21 of file lavaScript\&.cs\&.
.SS "float lavaScript\&.startHeight = \-10\&.0F"

.PP
height value of lava plane when it starts 
.PP
Definition at line 16 of file lavaScript\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FloorIsLava from the source code\&.
