.TH "Assets/Scripts/PC_MouseLook.cs" 3 "Wed Nov 25 2020" "Version 1.0" "FloorIsLava" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets/Scripts/PC_MouseLook.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPC_MouseLook\fP"
.br
.RI "Class for controlling camera on PC (mouse input) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FloorIsLava from the source code\&.
