.TH "PC_Movement" 3 "Tue Nov 24 2020" "Version 1.0" "FloorIsLava" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC_Movement \- Class for PC movement of player (keyboard)  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Rigidbody \fBplayerBody\fP"
.br
.RI "ref to player rigidbody for physics "
.ti -1c
.RI "Transform \fBplayerTransform\fP"
.br
.RI "ref to player transform for movement "
.ti -1c
.RI "float \fBjumpForce\fP"
.br
.RI "editable value to determine the power of the players jump "
.ti -1c
.RI "float \fBwalkSpeed\fP"
.br
.RI "editable value to determine the speed of player movement "
.ti -1c
.RI "float \fBmaxVel\fP"
.br
.RI "editable value to determine the players maximum horizontal velocity "
.in -1c
.SH "Detailed Description"
.PP 
Class for PC movement of player (keyboard) 


.PP
Definition at line 6 of file PC_Movement\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float PC_Movement\&.jumpForce"

.PP
editable value to determine the power of the players jump 
.PP
Definition at line 21 of file PC_Movement\&.cs\&.
.SS "float PC_Movement\&.maxVel"

.PP
editable value to determine the players maximum horizontal velocity 
.PP
Definition at line 31 of file PC_Movement\&.cs\&.
.SS "Rigidbody PC_Movement\&.playerBody"

.PP
ref to player rigidbody for physics 
.PP
Definition at line 11 of file PC_Movement\&.cs\&.
.SS "Transform PC_Movement\&.playerTransform"

.PP
ref to player transform for movement 
.PP
Definition at line 16 of file PC_Movement\&.cs\&.
.SS "float PC_Movement\&.walkSpeed"

.PP
editable value to determine the speed of player movement 
.PP
Definition at line 26 of file PC_Movement\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FloorIsLava from the source code\&.
