.TH "PlayerScript" 3 "Thu Nov 26 2020" "Version 1.0" "FloorIsLava" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerScript \- Script for controlling core player logic  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCanvasScript\fP \fBcs\fP"
.br
.RI "Canvas reference for UI events "
.ti -1c
.RI "GameObject \fBplayer\fP"
.br
.RI "Reference to player gameobject "
.ti -1c
.RI "int \fBmaxRespawnTicks\fP = 500"
.br
.RI "Number of updates that need to pass after win/loss before game restarts "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.RI "Function increases ticksSinceWinLoss var if hasWonOrLost is equal to TRUE\&. Once ticksSinceWinLoss is equal or greater than maxRespawnTicks, the game is unpaused and restarted\&. "
.ti -1c
.RI "void \fBOnTriggerEnter\fP (Collider other)"
.br
.RI "Checks if player has touched either the lava plane or the finish trigger\&. Depending which, will pause the game and call cs\&.onWin()/cs\&.onLoss()\&. Sets hasWonOrLost to TRUE and sets Time\&.timeScale to 0 to effectively pause game untill respawn\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBticksSinceWinLoss\fP = 0"
.br
.RI "Number of updates that have passed since a win/loss event "
.ti -1c
.RI "bool \fBhasWonOrLost\fP = false"
.br
.RI "Boolean for if the player has won or lost\&. "
.in -1c
.SH "Detailed Description"
.PP 
Script for controlling core player logic 


.PP
Definition at line 7 of file PlayerScript\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void PlayerScript\&.OnTriggerEnter (Collider other)\fC [private]\fP"

.PP
Checks if player has touched either the lava plane or the finish trigger\&. Depending which, will pause the game and call cs\&.onWin()/cs\&.onLoss()\&. Sets hasWonOrLost to TRUE and sets Time\&.timeScale to 0 to effectively pause game untill respawn\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP Object collided with
.RE
.PP

.PP
Definition at line 58 of file PlayerScript\&.cs\&.
.PP
.nf
59     {
60         if (other\&.tag == "Finish")//end touch
61         {
62             cs\&.onWin();
63             hasWonOrLost = true;
64             Time\&.timeScale = 0;
65         }
66         else if (other\&.tag == "Respawn")//lava touch
67         {
68             cs\&.onLoss();
69             hasWonOrLost = true;
70             Time\&.timeScale = 0;
71         }
72     }
.fi
.SS "void PlayerScript\&.Update ()\fC [private]\fP"

.PP
Function increases ticksSinceWinLoss var if hasWonOrLost is equal to TRUE\&. Once ticksSinceWinLoss is equal or greater than maxRespawnTicks, the game is unpaused and restarted\&. 
.PP
Definition at line 38 of file PlayerScript\&.cs\&.
.PP
.nf
39     {
40         if(hasWonOrLost)
41         {
42             ticksSinceWinLoss++;
43             if(ticksSinceWinLoss >= maxRespawnTicks)
44             {
45                 ticksSinceWinLoss = 0;
46                 Time\&.timeScale = 1;
47                 SceneManager\&.LoadScene(SceneManager\&.GetActiveScene()\&.name);
48             }
49         }
50     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBCanvasScript\fP PlayerScript\&.cs"

.PP
Canvas reference for UI events 
.PP
Definition at line 12 of file PlayerScript\&.cs\&.
.SS "bool PlayerScript\&.hasWonOrLost = false\fC [private]\fP"

.PP
Boolean for if the player has won or lost\&. 
.PP
Definition at line 32 of file PlayerScript\&.cs\&.
.SS "int PlayerScript\&.maxRespawnTicks = 500"

.PP
Number of updates that need to pass after win/loss before game restarts 
.PP
Definition at line 27 of file PlayerScript\&.cs\&.
.SS "GameObject PlayerScript\&.player"

.PP
Reference to player gameobject 
.PP
Definition at line 17 of file PlayerScript\&.cs\&.
.SS "int PlayerScript\&.ticksSinceWinLoss = 0\fC [private]\fP"

.PP
Number of updates that have passed since a win/loss event 
.PP
Definition at line 22 of file PlayerScript\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FloorIsLava from the source code\&.
