.TH "PlayerScript" 3 "Tue Nov 24 2020" "Version 1.0" "FloorIsLava" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerScript \- Script for controlling core player logic  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCanvasScript\fP \fBcs\fP"
.br
.RI "Canvas reference for UI events "
.ti -1c
.RI "GameObject \fBplayer\fP"
.br
.RI "Reference to player gameobject "
.ti -1c
.RI "int \fBmaxRespawnTicks\fP = 500"
.br
.RI "Number of updates that need to pass after win/loss before game restarts "
.in -1c
.SH "Detailed Description"
.PP 
Script for controlling core player logic 


.PP
Definition at line 7 of file PlayerScript\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCanvasScript\fP PlayerScript\&.cs"

.PP
Canvas reference for UI events 
.PP
Definition at line 12 of file PlayerScript\&.cs\&.
.SS "int PlayerScript\&.maxRespawnTicks = 500"

.PP
Number of updates that need to pass after win/loss before game restarts 
.PP
Definition at line 27 of file PlayerScript\&.cs\&.
.SS "GameObject PlayerScript\&.player"

.PP
Reference to player gameobject 
.PP
Definition at line 17 of file PlayerScript\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FloorIsLava from the source code\&.
