.TH "TouchButton" 3 "Thu Nov 26 2020" "Version 1.0" "FloorIsLava" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TouchButton \- Customized button extension for work with android touch screens  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Button\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPointerDown\fP (PointerEventData eventData)"
.br
.RI "Requred to override base button function for integration with project "
.ti -1c
.RI "override void \fBOnPointerUp\fP (PointerEventData eventData)"
.br
.RI "Requred to override base button function for integration with project "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "UnityEvent \fBonButDown\fP\fC [get]\fP"
.br
.ti -1c
.RI "UnityEvent \fBonButUp\fP\fC [get]\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "UnityEvent \fBonButtonDown\fP = new UnityEvent()"
.br
.RI "Event for when this button is first pressed down "
.ti -1c
.RI "UnityEvent \fBonButtonUp\fP = new UnityEvent()"
.br
.RI "Event for when this button is released "
.in -1c
.SH "Detailed Description"
.PP 
Customized button extension for work with android touch screens 


.PP
Definition at line 10 of file TouchButton\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TouchButton\&.OnPointerDown (PointerEventData eventData)"

.PP
Requred to override base button function for integration with project 
.PP
Definition at line 24 of file TouchButton\&.cs\&.
.PP
.nf
25     {
26         base\&.OnPointerDown(eventData);
27         onButtonDown\&.Invoke();
28     }
.fi
.SS "override void TouchButton\&.OnPointerUp (PointerEventData eventData)"

.PP
Requred to override base button function for integration with project 
.PP
Definition at line 33 of file TouchButton\&.cs\&.
.PP
.nf
34     {
35         base\&.OnPointerUp(eventData);
36         onButtonUp\&.Invoke();
37     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "UnityEvent TouchButton\&.onButtonDown = new UnityEvent()\fC [private]\fP"

.PP
Event for when this button is first pressed down 
.PP
Definition at line 15 of file TouchButton\&.cs\&.
.SS "UnityEvent TouchButton\&.onButtonUp = new UnityEvent()\fC [private]\fP"

.PP
Event for when this button is released 
.PP
Definition at line 20 of file TouchButton\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "UnityEvent TouchButton\&.onButDown\fC [get]\fP"

.PP
Definition at line 39 of file TouchButton\&.cs\&.
.PP
.nf
40     {
41          get => onButtonDown; 
42     }
.fi
.SS "UnityEvent TouchButton\&.onButUp\fC [get]\fP"

.PP
Definition at line 43 of file TouchButton\&.cs\&.
.PP
.nf
44     {
45         get => onButtonUp;
46     }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for FloorIsLava from the source code\&.
